#!/usr/bin/env bash
# Generate backend_v2/.env.prod: random infra passwords + OpenAI/Tavily copied
# from backend_v2/.env. Never prints secret values. FORCE=1 overwrites.
set -euo pipefail
cd "$(dirname "$0")/../.."   # repo root

OUT=backend_v2/.env.prod
SRC=backend_v2/.env

if [[ -f "$OUT" && "${FORCE:-0}" != "1" ]]; then
  echo "gen-prod-env: $OUT already exists — leaving it untouched (FORCE=1 to regenerate)"
  exit 0
fi

val() { grep -E "^$1=" "$SRC" 2>/dev/null | head -1 | cut -d= -f2- || true; }

PG_PW=$(openssl rand -hex 16)
NEO_PW=$(openssl rand -hex 16)
ADMIN=$(openssl rand -hex 16)
OPENAI=$(val OPENAI_API_KEY)
TAVILY=$(val TAVILY_API_KEY)

umask 077
cat > "$OUT" <<EOF
# Aladin PROD config — generated by scripts/ops/gen_prod_env.sh. Gitignored.
# Hostnames are compose service names (internal network), not localhost.
POSTGRES_PASSWORD=$PG_PW
DATABASE_URL=postgres://aladin:$PG_PW@postgres:5432/aladin?sslmode=disable
REDIS_URL=redis://redis:6379/0
NEO4J_PASSWORD=$NEO_PW
NEO4J_URI=bolt://neo4j:7687
NEO4J_USER=neo4j
NEO4J_PASS=$NEO_PW
OPENAI_API_KEY=$OPENAI
TAVILY_API_KEY=$TAVILY
ALPACA_API_KEY=
ALPACA_API_SECRET=
BLOCKNOTE_ADMIN_SHARED_SECRET=$ADMIN
LOG_LEVEL=info
WORKER_CONCURRENCY=16
NGROK_AUTOSTART=0
EOF
chmod 600 "$OUT"

echo "gen-prod-env: wrote $OUT (infra passwords generated; OpenAI/Tavily copied from $SRC)"
if [[ -z "$OPENAI" ]]; then
  echo "gen-prod-env: WARNING — OPENAI_API_KEY is empty; the worker needs it. Set it in $OUT." >&2
fi
