package ingestion

import (
	"path/filepath"
	"strings"
	"testing"
)

// The fixtures are small real PDFs, generated by tools/pdftoc/make_fixture.py:
//
//	plain.pdf     10 pages of text, NO bookmarks
//	outlined.pdf  the same book after pdftoc wrote an outline into it
//	scanlike.pdf  4 pages of pure graphics — no text layer, i.e. what a scan looks like
//	corrupt.pdf   not a PDF at all
//
// Real files rather than mocks because every interesting failure here lives in the
// format, not in our control flow.

func fixture(name string) string { return filepath.Join("testdata", name) }

func TestExtractPDF_Text(t *testing.T) {
	doc := ExtractPDF(fixture("plain.pdf"))

	if doc.Status != StatusReady {
		t.Fatalf("status = %q (%s), want ready", doc.Status, doc.Error)
	}
	if doc.PageCount != 10 {
		t.Fatalf("page count = %d, want 10", doc.PageCount)
	}
	if len(doc.Pages) != 10 {
		t.Fatalf("pages = %d, want one entry per page", len(doc.Pages))
	}
	// Per-page, not one blob — a section knows only its page, so it has to resolve here.
	if doc.Pages[4].Page != 5 {
		t.Fatalf("page numbering is 1-based: got %d at index 4", doc.Pages[4].Page)
	}
	if !strings.Contains(doc.Pages[4].Text, "Beginnings") {
		t.Fatalf("page 5 text = %q, want the chapter heading", doc.Pages[4].Text)
	}
	if doc.Extractor == "" {
		t.Fatal("extractor must be stamped so a better one can re-run stale rows")
	}
}

func TestExtractPDF_OutlineFromBookmarks(t *testing.T) {
	doc := ExtractPDF(fixture("outlined.pdf"))

	if doc.Status != StatusReady {
		t.Fatalf("status = %q (%s), want ready", doc.Status, doc.Error)
	}
	if len(doc.Sections) != 7 {
		t.Fatalf("sections = %d, want 7: %+v", len(doc.Sections), doc.Sections)
	}

	first := doc.Sections[0]
	if first.Title != "Preface" || first.Level != 0 || first.Page != 4 {
		t.Fatalf("first section = %+v, want Preface at level 0 page 4", first)
	}
	// Nesting must survive: 1.1 belongs under 1 Beginnings.
	nested := doc.Sections[2]
	if nested.Level != 1 || !strings.Contains(nested.Title, "First light") {
		t.Fatalf("third section = %+v, want a level-1 child", nested)
	}
	for _, section := range doc.Sections {
		if section.Page < 1 || section.Page > doc.PageCount {
			t.Fatalf("section %+v points outside 1..%d", section, doc.PageCount)
		}
	}
}

// A PDF with no bookmarks is a perfectly good document — §5 says we leave the outline
// empty rather than inventing one, and it must NOT be treated as a failure.
func TestExtractPDF_NoOutlineIsNotAFailure(t *testing.T) {
	doc := ExtractPDF(fixture("plain.pdf"))
	if doc.Status != StatusReady {
		t.Fatalf("status = %q, want ready", doc.Status)
	}
	if len(doc.Sections) != 0 {
		t.Fatalf("sections = %+v, want none invented", doc.Sections)
	}
}

// §4's load-bearing case. A scan is not a crash and not a success: reporting it as ready
// with zero text is a lie, and reporting it as failed sends you debugging the file.
func TestExtractPDF_ScanIsUnsupportedNotFailed(t *testing.T) {
	doc := ExtractPDF(fixture("scanlike.pdf"))

	if doc.Status != StatusUnsupported {
		t.Fatalf("status = %q (%s), want unsupported", doc.Status, doc.Error)
	}
	if doc.PageCount == 0 {
		t.Fatal("the pages exist and were counted — only the text layer is missing")
	}
	// The message has to name the next action, or the status is just a different spinner.
	if !strings.Contains(strings.ToLower(doc.Error), "ocr") {
		t.Fatalf("error = %q, want it to point at OCR", doc.Error)
	}
}

func TestExtractPDF_CorruptIsFailedWithAReason(t *testing.T) {
	doc := ExtractPDF(fixture("corrupt.pdf"))

	if doc.Status != StatusFailed {
		t.Fatalf("status = %q, want failed", doc.Status)
	}
	if doc.Error == "" {
		t.Fatal("a failure with no reason is undebuggable")
	}
}

func TestExtractPDF_MissingAndEmpty(t *testing.T) {
	missing := ExtractPDF(fixture("does-not-exist.pdf"))
	if missing.Status != StatusFailed || missing.Error == "" {
		t.Fatalf("missing file = %+v, want failed with a reason", missing)
	}

	empty := ExtractPDF(fixture("empty-fixture.pdf"))
	if empty.Status != StatusFailed {
		t.Fatalf("empty file = %+v, want failed", empty)
	}
}

func TestNormalizeCollapsesExtractionWhitespace(t *testing.T) {
	// PDF text comes out positionally, so runs of spaces and blank lines are artefacts
	// of glyph placement rather than meaning.
	got := normalize("  Hello   world  \n\n\n   second   line \n  ")
	if got != "Hello world\nsecond line" {
		t.Fatalf("normalize = %q", got)
	}
}
