package llm

import (
	"context"

	"github.com/openai/openai-go"
	"github.com/openai/openai-go/option"
	"github.com/openai/openai-go/shared"
)

// ChatAgent is the conversational, streaming, tool-use LLM surface — the one the
// Copilot agent loop drives. It is deliberately separate from the single-shot
// structured-output judges in openai.go (Enricher/RelevanceJudge/…): those map one
// prompt to one JSON blob; this streams a back-and-forth turn where the model may
// call tools, we run them, feed results back, and call Chat again until it stops.
type ChatAgent interface {
	// Chat streams one assistant turn. onEvent fires for each text delta and each
	// completed tool call, in stream order. It returns the finished assistant message
	// (Content plus any ToolCalls) to append to the running history.
	Chat(ctx context.Context, messages []ChatMessage, tools []ChatToolDef, onEvent func(ChatEvent)) (ChatMessage, error)
}

// ChatRole is the author of a conversational turn.
type ChatRole string

const (
	ChatRoleSystem    ChatRole = "system"
	ChatRoleUser      ChatRole = "user"
	ChatRoleAssistant ChatRole = "assistant"
	ChatRoleTool      ChatRole = "tool"
)

// ChatToolCall is a model request to invoke a tool (or, in history, the record of one).
type ChatToolCall struct {
	ID        string
	Name      string
	Arguments string // raw JSON, as generated by the model — validate before use
}

// ChatMessage is one turn in the conversation passed to (and returned from) the agent.
type ChatMessage struct {
	Role    ChatRole
	Content string
	// ToolCalls is set on an assistant turn that requested tools.
	ToolCalls []ChatToolCall
	// ToolCallID identifies which tool call a ChatRoleTool result answers.
	ToolCallID string
}

// ChatToolDef is a tool the model may call. Parameters is a JSON Schema object.
type ChatToolDef struct {
	Name        string
	Description string
	Parameters  map[string]any
}

// ChatEventKind discriminates a streamed event.
type ChatEventKind int

const (
	ChatEventText ChatEventKind = iota
	ChatEventToolCall
)

// ChatEvent is one streamed item: a text delta or a completed tool call.
type ChatEvent struct {
	Kind     ChatEventKind
	Text     string       // set when Kind == ChatEventText
	ToolCall ChatToolCall // set when Kind == ChatEventToolCall
}

// OpenAIChatAgent implements ChatAgent over the OpenAI Chat Completions streaming API,
// reusing the same client/key the rest of the llm package uses.
type OpenAIChatAgent struct {
	client openai.Client
	model  string
}

func NewOpenAIChatAgent(apiKey, model string) *OpenAIChatAgent {
	return &OpenAIChatAgent{
		client: openai.NewClient(option.WithAPIKey(apiKey)),
		model:  model,
	}
}

func (a *OpenAIChatAgent) Chat(ctx context.Context, messages []ChatMessage, tools []ChatToolDef, onEvent func(ChatEvent)) (ChatMessage, error) {
	params := openai.ChatCompletionNewParams{
		Model:    openai.ChatModel(a.model),
		Messages: toOpenAIMessages(messages),
		// Sequential tool calls: JustFinishedToolCall on the accumulator is only reliable
		// with parallel tool calls disabled. One tool at a time keeps the loop simple + correct.
		ParallelToolCalls: openai.Bool(false),
	}
	if len(tools) > 0 {
		params.Tools = toOpenAITools(tools)
	}

	stream := a.client.Chat.Completions.NewStreaming(ctx, params)
	defer stream.Close()

	acc := openai.ChatCompletionAccumulator{}
	for stream.Next() {
		chunk := stream.Current()
		acc.AddChunk(chunk)
		if len(chunk.Choices) > 0 {
			if delta := chunk.Choices[0].Delta.Content; delta != "" && onEvent != nil {
				onEvent(ChatEvent{Kind: ChatEventText, Text: delta})
			}
		}
		if tc, ok := acc.JustFinishedToolCall(); ok && onEvent != nil {
			onEvent(ChatEvent{Kind: ChatEventToolCall, ToolCall: ChatToolCall{
				ID: tc.ID, Name: tc.Name, Arguments: tc.Arguments,
			}})
		}
	}
	if err := stream.Err(); err != nil {
		return ChatMessage{}, err
	}
	if len(acc.Choices) == 0 {
		return ChatMessage{Role: ChatRoleAssistant}, nil
	}

	msg := acc.Choices[0].Message
	out := ChatMessage{Role: ChatRoleAssistant, Content: msg.Content}
	for _, tc := range msg.ToolCalls {
		out.ToolCalls = append(out.ToolCalls, ChatToolCall{
			ID: tc.ID, Name: tc.Function.Name, Arguments: tc.Function.Arguments,
		})
	}
	return out, nil
}

func toOpenAIMessages(msgs []ChatMessage) []openai.ChatCompletionMessageParamUnion {
	out := make([]openai.ChatCompletionMessageParamUnion, 0, len(msgs))
	for _, m := range msgs {
		switch m.Role {
		case ChatRoleSystem:
			out = append(out, openai.SystemMessage(m.Content))
		case ChatRoleUser:
			out = append(out, openai.UserMessage(m.Content))
		case ChatRoleTool:
			out = append(out, openai.ToolMessage(m.Content, m.ToolCallID))
		case ChatRoleAssistant:
			if len(m.ToolCalls) == 0 {
				out = append(out, openai.AssistantMessage(m.Content))
				continue
			}
			asst := openai.ChatCompletionAssistantMessageParam{}
			if m.Content != "" {
				asst.Content.OfString = openai.String(m.Content)
			}
			for _, tc := range m.ToolCalls {
				asst.ToolCalls = append(asst.ToolCalls, openai.ChatCompletionMessageToolCallParam{
					ID: tc.ID,
					Function: openai.ChatCompletionMessageToolCallFunctionParam{
						Name:      tc.Name,
						Arguments: tc.Arguments,
					},
				})
			}
			out = append(out, openai.ChatCompletionMessageParamUnion{OfAssistant: &asst})
		}
	}
	return out
}

func toOpenAITools(tools []ChatToolDef) []openai.ChatCompletionToolParam {
	out := make([]openai.ChatCompletionToolParam, 0, len(tools))
	for _, t := range tools {
		out = append(out, openai.ChatCompletionToolParam{
			Function: shared.FunctionDefinitionParam{
				Name:        t.Name,
				Description: openai.String(t.Description),
				Parameters:  shared.FunctionParameters(t.Parameters),
			},
		})
	}
	return out
}
