import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { createPortal } from "react-dom";
import { useState } from "react";
export default function App({ title = "Artifact web view prototype", kind = "artifact", overlayRoot = null, }) {
    const [showOverlay, setShowOverlay] = useState(false);
    return (_jsxs(_Fragment, { children: [_jsx("main", { className: "app-shell", children: _jsxs("article", { className: "document-page", children: [_jsxs("header", { className: "document-header", children: [_jsxs("div", { className: "document-meta-row", children: [_jsx("span", { children: kind }), _jsx("span", { children: "local draft" })] }), _jsxs("div", { className: "document-title-row", children: [_jsx("h1", { children: title }), _jsx("button", { className: "overlay-toggle", type: "button", onClick: () => setShowOverlay((value) => !value), children: showOverlay ? "Hide probe" : "Probe" })] })] }), _jsxs("section", { className: "document-body", children: [_jsx("p", { className: "document-lead", children: "This surface is deliberately quiet. It should read like the beginning of a writing canvas, with just enough context to orient the document before the editor takes over." }), _jsx("p", { children: "Pane 3 now behaves like a document window: tabs at the top, a compact internal header, and the working surface starting almost immediately below it. The next step is to replace this stub with the actual markdown editor." }), _jsx("p", { children: "Graph mode can reuse the same bounded-canvas model later, keeping local overlays and interactions inside the pane instead of letting the shell dominate the experience." })] })] }) }), showOverlay &&
                overlayRoot &&
                createPortal(_jsx("div", { className: "boundary-overlay-shell", onClick: () => setShowOverlay(false), children: _jsxs("div", { className: "boundary-overlay-card", onClick: (event) => event.stopPropagation(), children: [_jsx("div", { className: "panel-label", children: "REACT PORTAL OVERLAY" }), _jsx("h2", { children: "Cross-boundary overlay probe" }), _jsx("p", { children: "This overlay is rendered by React outside the embedded artifact root. If you can see it covering the folder browser or top bar, the React side can own overlays above Compose surfaces." }), _jsx("button", { className: "overlay-toggle", type: "button", onClick: () => setShowOverlay(false), children: "Close overlay" })] }) }), overlayRoot)] }));
}
